Otiva/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'annonce' => 'pages#annonce'
  post 'annonce' => 'pages#creation_ann'

  get 'login' => 'pages#login'
  post 'login' => 'pages#verif'
  delete 'login' => 'pages#deco'

  get 'inscription' => 'pages#inscription'
  post 'inscription' => 'pages#insertion'
  
  get 'mes_annonces' => 'pages#mes_annonces'
  delete 'mes_annonces' => 'pages#supr_prod'

  get 'modifier_annonce' => 'pages#modifier_annonce'
  post 'modifier_annonce' => 'pages#modif_ann'

  get 'admin' => 'pages#admin'
  delete 'admin' => 'pages#supr_prod'

  get 'qui' => 'pages#qui'
 resources :chercherproduit
  

end

Otiva/app/models/produit.rb
class Produit < ActiveRecord::Base
	belongs_to :utilisateurs
end

Otiva/app/models/utilisateur.rb
class Utilisateur < ActiveRecord::Base
	has_many :produits
end

Otiva/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
end

Otiva/app/controllers/chercherproduit_controller.rb
class ChercherproduitController < ApplicationController
    
  def index
    if session[:util_id]
        @util_courant=Utilisateur.find(session[:util_id])
    end
    if params[:ville] == "*"
      
        unless params[:categorie].empty?
            unless params[:titre].empty?
                @produits = Produit.where("titre LIKE '%#{params[:titre]}%' AND genre = ?
                AND categorie = ?",params[:genre] ,params[:categorie]).paginate(:page => params[:page], :per_page => 3)
            else
              @produits = Produit.where(genre: params[:genre],categorie: params[:categorie]).paginate(:page => params[:page], :per_page => 3)
            end
        else
            unless params[:titre].empty?
                @produits = Produit.where("titre LIKE '%#{params[:titre]}%' AND genre = ?",
                params[:genre]).paginate(:page => params[:page], :per_page => 3)
            else
                @produits = Produit.where(genre: params[:genre]).paginate(:page => params[:page], :per_page => 3)
            end
        end
    else
        unless params[:categorie].empty?
            unless params[:titre].empty?
                @produits = Produit.where("titre LIKE '%#{params[:titre]}%' AND genre = ?
                AND categorie = ? AND ville = ?",params[:genre] ,params[:categorie], params[:ville]).paginate(:page => params[:page], :per_page => 3)
            else
              @produits = Produit.where(genre: params[:genre],categorie: params[:categorie], ville: params[:ville])
              .paginate(:page => params[:page], :per_page => 3)
            end
        else
            unless params[:titre].empty?
                @produits = Produit.where("titre LIKE '%#{params[:titre]}%' AND genre = ? AND ville = ?",
                params[:genre], params[:ville]).paginate(:page => params[:page], :per_page => 3)
            else
                @produits = Produit.where(genre: params[:genre], ville: params[:ville]).
                paginate(:page => params[:page], :per_page => 3)
            end
        end
      end

    end


  def show
    if session[:util_id]
        @util_courant=Utilisateur.find(session[:util_id])
    end
    @produits = Produit.where(id: params[:id])
    @produits.each do |pr| 
        @util=Utilisateur.where(id:pr.utilisateur_id)
        @product=Produit.where("categorie = ? AND NOT id = ?",pr.categorie,pr.id).limit(1)
    end
    #@produits = Produit.where("id = ? AND genre = ?", params[:id], params[:genre])
    
  end 
  def destroy
    session[:util_id] = nil
    redirect_to root_path
  end

end

Otiva/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	if session[:util_id]
  		@util_courant=Utilisateur.find(session[:util_id])
  	end
    @produit=Produit.all
  end
  def annonce
    if session[:util_id]
      @util_courant=Utilisateur.find(session[:util_id])
    end
  end
  def creation_ann
    if !session[:util_id]
      inser_prod
      inser_user
      user_id=Utilisateur.find_by_name(params[:name]).id
      Produit.find_by_titre(params[:titre]).update utilisateur_id: user_id
      redirect_to root_path
    else
      inser_prod
      redirect_to root_path
    end
  end
  def inser_prod
    uploaded_io = params[:photo]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    file.write(uploaded_io.read)
    end
    Produit.create categorie: params[:categorie],ville: params[:ville],genre: params[:genre],
                    titre: params[:titre],description: params[:description],
                    prix: params[:prix],photo: uploaded_io.original_filename,
                    utilisateur_id: session[:util_id]
  end
  def inser_user
    Utilisateur.create name: params[:name],password: params[:password],
                      email: params[:email],tel: params[:tel],
                      status: params[:statut],ville: params[:ville]

  end
  def insertion
    inser_user
    redirect_to login_path
  end
  def supr_prod
    Produit.find(params[:id]).destroy
    @util_courant=Utilisateur.find(session[:util_id])
    if @util_courant.admin?
      redirect_to admin_path
    else
      redirect_to mes_annonces_path
    end
  end
  def mes_annonces
    @produit=Produit.where(utilisateur_id:session[:util_id])
    if session[:util_id]
      @util_courant=Utilisateur.find(session[:util_id])
    end
  end
  def modifier_annonce
    if session[:util_id]
      @util_courant=Utilisateur.find(session[:util_id])
    end
  end
  def modif_ann
    uploaded_io = params[:photo]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    file.write(uploaded_io.read)
    end
        Produit.find(params[:id]).update categorie: params[:categorie],ville: params[:ville],genre: params[:genre],
                    titre: params[:titre],description: params[:description],
                    prix: params[:prix],photo: uploaded_io.original_filename
    @util_courant=Utilisateur.find(session[:util_id])
    if @util_courant.admin?
      redirect_to admin_path
    else
      redirect_to mes_annonces_path
    end
  end
  def login
  end
  def inscription
  end

  def admin
    @util_courant=Utilisateur.find(session[:util_id])
    @produit=Produit.all
  end

  def verif
  	@util_courant = Utilisateur.where(name: params[:name], password: params[:password]).first
    if @util_courant
      session[:util_id]=@util_courant.id
      redirect_to root_path
    else
      session[:util_id]=nil
      redirect_to "/login"
    end
  end
  def deco
  	session[:util_id] = nil
    redirect_to root_path
  end
  def qui
    if session[:util_id]
      @util_courant=Utilisateur.find(session[:util_id])
    end
  end
end

Otiva/app/helpers/application_helper.rb
module ApplicationHelper
end

Otiva/app/helpers/chercherproduit_helper.rb
module ChercherproduitHelper
end

Otiva/app/helpers/pages_helper.rb
module PagesHelper
end

Otiva/app/helpers/users_helper.rb
module UsersHelper
end

Otiva/app/views/chercherproduit/index.html.erb
<% if session[:util_id] %>
	<%= render partial: 'pages/nav2', locals: {util_courant: @util_courant} %>
<% else %>
	<%= render "pages/nav" %>
<% end %>

<div class="container">



	
		<h2 class="title text-center">NOS ANNONCES</h2>
	</div>
<% @produits.each do |produit| %>
	<section>
<div class="container">
<div class="row">
<div class="col-sm-3">
	
		
		
	</div>

<div class="col-sm-9">
	<div class="blog-post-area">
		

		<div class="single-blog-post">
			<h3><%= produit.titre %></h3>
			<div class="post-meta">
				<ul>
					
					<li><i>Date</i>
					<%
						tab = produit.created_at.to_s.split(' ')
					%>
					<b><%=	tab[0] %></b>
					</li>
					<li><i>Heure</i>
					 <b><%= tab[1] %></b>
					</li>
				</ul>
				
			</div>
			<a href="">
				<%= image_tag "/uploads/"+produit.photo %>
				
			</a>
			<p><%= produit.description %></p>
			<%= form_tag "chercherproduit/#{produit.id}", method: :get do  %>
			<%= hidden_field_tag :id, produit.id %>

	<div style="margin-left:40%;">		
		<%= submit_tag "Plus", class:"z" %>	</div>
 					 <br/>
			<% end %>
		</div>
		
			
		
		
	</div>
</div>
</div>
</div>
</section>
	
	<% end %>
	<div class="container" style="margin-left:35%;margin-top: 2%;">
		<div class="pagination-area">

			<ul class="pagination">
				<li><%= will_paginate @produits %></li>
				<!-- <li><a href="" class="active">1</a></li>
				<li><a href="">2</a></li>
				<li><a href="">3</a></li>
				<li><a href=""><i class="fa fa-angle-double-right"></i></a></li> -->
			</ul>
		</div>
		</div>



	

  

Otiva/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Otiva</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


		
	<footer id="footer"><!--Footer-->
		
		<div class="footer-widget" style="margin-left: 30%;">
			<div class="container">
				<div class="row">
				<div class="col-sm-2">
						<div class="single-widget">
							<%= image_tag "images/logo.png",height:100,width:100 %>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Commençons</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><%= link_to 'Accueil', root_path,class:"d" %></li>
		                        <li><%= link_to 'Connexion', login_path,class:"d" %></li>
		                    </ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>A propos de nous</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><%= link_to 'Qui sommes-nous ?', qui_path,class:"d" %></li>
		                        
		                    </ul>
						</div>
					</div>
					
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2018 OTIVA Inc. All rights reserved.</p>
				</div>
			</div>
		</div>
		
	</footer>	
</body>
</html>

Otiva/app/views/pages/_nav.html.erb
<div class="header-bottom">
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div  style="margin-right: 5%;" class="navbar-header">
							
						<%= image_tag "images/logo.png",height:100,width:100 %>

						</div>
						<br/><br/>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a><%= link_to 'Accueil', root_path %></a></li>
								  <li><a><%= link_to 'Mes annonces', login_path %></a></li>
								  <li><a><%= link_to 'A propos', qui_path %></a></li>
								  <li id="trait"><a><%= link_to 'Se connecter', login_path %></a></li>
								
							</ul>
						</div>
					</div>
					<br/><br/>
					<div class="col-sm-3">
						<div class="search_box pull-right">

							<li><%= link_to 'Déposer une annonce', annonce_path,class:"d" %></li>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
	<br/>
<%= form_tag "chercherproduit", method: :get do  %>

<!-- <input type="text" name="text" id="text" class="form-control input-lg" style="width: 20%; display: inline-block; margin-left: 20%;" placeholder="Que Recherchez-Vous ?"> -->
<div id="text" style="width: 20%; display: inline-block; margin-left: 20%;">
<%= text_field_tag :titre, params[:titre], class: 'form-control input-lg' %>	
</div>


<select name="categorie" class="form-control input-lg" style="width: 20%; display: inline-block;" id="inputState" class="form-control">
	<option value="" selected>Toutes les catégories</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="5000">-- INFORMATIQUE ET MULTIMEDIA --</option>
	<option value="Telephones">Téléphones</option>
	<option value="Tablettes">Tablettes</option>
	<option value="Ordinateurs portables">Ordinateurs portables</option>
	<option value="Ordinateurs de bureau">Ordinateurs de bureau</option>
	<option value="Accessoires informatique et Gadgets">Accessoires informatique et Gadgets</option>
	<option value="Jeux vidéo et Consoles">Jeux vidéo et Consoles</option>
	<option value="Appareils photo et Caméras70">Appareils photo et Caméras</option>
	<option value="Télévisions">Télévisions</option>
	<option value="Image & Son">Image &amp; Son</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="2000">-- VEHICULES --</option>
	<option value="Voitures">Voitures</option>
	<option value="Motos">Motos</option>
	<option value="Vélos">Vélos</option>
	<option value="Véhicules Professionnels">Véhicules Professionnels</option>
	<option value="Bateaux">Bateaux</option>
	<option value="Pièces et Accessoires pour véhicules">Pièces et Accessoires pour véhicules</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="1000">-- IMMOBILIER --</option>
	<option value="Appartements">Appartements</option>
	<option value="Maisons et Villas">Maisons et Villas</option>
	<option value="Bureaux et Plateaux">Bureaux et Plateaux</option>
	<option value="Magasins, Commerces et Locaux industriels">Magasins, Commerces et Locaux industriels</option>
	<option value="Terrains et Fermes">Terrains et Fermes</option>
	<option value="Locations de vacances">Locations de vacances</option>
	<option value="Colocations">Colocations</option>
	<option value="Autre Immobilier">Autre Immobilier</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="3000">-- POUR LA MAISON ET JARDIN --</option>
	<option value="Electroménager et Vaisselles">Electroménager et Vaisselles</option>
	<option value="Meubles et Décoration">Meubles et Décoration</option>
	<option value="Jardin et Outils de bricolage">Jardin et Outils de bricolage</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="8000">-- HABILLEMENT ET BIEN ETRE --</option>
	<option value="Vêtements">Vêtements</option>
	<option value="Chaussures">Chaussures</option>
	<option value="Montres et Bijoux">Montres et Bijoux</option>
	<option value="Sacs et Accessoires">Sacs et Accessoires</option>
	<option value="3030">Vêtements pour enfant et bébé</option>
	<option value="3130">Equipements pour enfant et bébé</option>
	<option value="3070">Produits de beauté</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="4000">-- LOISIRS ET DIVERTISSEMENT --</option>
	<option value="4010">Sports et Loisirs</option>
	<option value="Animaux">Animaux</option>
	<option value="4070">Instruments de Musique</option>
	<option value="4060">Art et Collections</option>
	<option value="4050">Voyages et Billetterie</option>
	<option value="4040">Films, Livres, Magazines</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="6000">-- EMPLOI ET SERVICES --</option>
	<option value="6010">Offres d'emploi</option>
	<option value="6020">Demandes d'emploi</option>
	<option value="Stages">Stages</option>
	<option value="Services">Services</option>
	<option value="Cours et Formations">Cours et Formations</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="9000">-- ENTREPRISES --</option>
	<option value="6100">Business et Affaires commerciales</option>
	<option value="6090">Matériels Professionnels</option>
	<option value="6120">Stocks et Vente en gros</option>
	


</select>

<select name="ville" class="form-control input-lg" style="width: 20%; display: inline-block;" id="inputState" class="form-control">
<option value="*" selected>Tout le Maroc</option>
<option value="Agadir"> Agadir</option>
<option value="Al Hoceïma"> Al Hoceïma</option>
<option value="Béni Mellal"> Béni Mellal</option>
<option value="El Jadida<"> El Jadida</option>
<option value="Errachidia"> Errachidia</option>
<option value="Fès"> Fès</option>
<option value="Kenitra"> Kénitra</option>
<option value="Khenifra"> Khénifra</option>
<option value="Khouribga"> Khouribga</option>
<option value="Larache"> Larache</option>
<option value="Marrakech"> Marrakech</option>
<option value="Meknès"> Meknès</option>
<option value="Nador"> Nador</option>
<option value="Ouarzazate"> Ouarzazate</option>
<option value="Oujda"> Oujda</option>
<option value="Rabat"> Rabat</option>
<option value="Safi"> Safi</option>
<option value="Settat"> Settat</option>
<option value="Salé"> Salé</option>
<option value="Tanger"> Tanger</option>
<option value="Taza"> Taza</option>
<option value="Tétouan"> Tétouan</option>
</select>
<div class="form-group" style="margin-left: 20%">
        <label><input name="genre" type="radio" value="offre" checked="checked">Offre</label>
    &nbsp;&nbsp;
      <label><input name="genre" type="radio" value="demande">Demande</label>
        

<li style="margin-left:46%;margin-top: 2%;display: inline-block;"><%= submit_tag "Rechercher", class:"z" %></li></div>

<% end %>

<br/><br/>

Otiva/app/views/pages/_nav2.html.erb
<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div  style="margin-right: 5%;" class="navbar-header">
							
						<%= image_tag "images/logo.png",height:100,width:100 %>

						</div>
						<br/><br/>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a><%= link_to 'Accueil', root_path %></a></li>
								<% if @util_courant.admin? %>
								  <li><a><%= link_to 'Espace Admin', admin_path %></a></li>
								<% else %>
								  <li><a><%= link_to 'Mes annonces', mes_annonces_path %></a></li>
								<% end %>
								  <li><a><%= link_to 'A propos', qui_path,class:"d" %></a></li>
								  <li ><a><%= form_tag "login", method: :delete do %>
								    <input type="submit" value="Déconnexion" />
								  <% end %></a></li>
								 
							</ul>
						</div>
					</div>
					<br/><br/>

					<div class="col-sm-3">
						<div class="search_box pull-right">
							<li><span class="d">Bonjour <%= util_courant.name %></span></li>
							<li><%= link_to 'Déposer une annonce', annonce_path,class:"d" %></li>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
	<br/>
	<div>

	<%= form_tag "chercherproduit", method: :get do  %>

<!-- <input type="text" name="text" id="text" class="form-control input-lg" style="width: 20%; display: inline-block; margin-left: 20%;" placeholder="Que Recherchez-Vous ?"> -->
<div id="text" style="width: 20%; display: inline-block; margin-left: 20%;">
<%= text_field_tag :titre, params[:titre], class: 'form-control input-lg' %>	
</div>


<select name="categorie" class="form-control input-lg" style="width: 20%; display: inline-block;" id="inputState" class="form-control">
	<option value="" selected>Toutes les catégories</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="5000">-- INFORMATIQUE ET MULTIMEDIA --</option>
	<option value="Telephones">Téléphones</option>
	<option value="Tablettes">Tablettes</option>
	<option value="Ordinateurs portables">Ordinateurs portables</option>
	<option value="Ordinateurs de bureau">Ordinateurs de bureau</option>
	<option value="Accessoires informatique et Gadgets">Accessoires informatique et Gadgets</option>
	<option value="Jeux vidéo et Consoles">Jeux vidéo et Consoles</option>
	<option value="Appareils photo et Caméras70">Appareils photo et Caméras</option>
	<option value="Télévisions">Télévisions</option>
	<option value="Image & Son">Image &amp; Son</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="2000">-- VEHICULES --</option>
	<option value="Voitures">Voitures</option>
	<option value="Motos">Motos</option>
	<option value="Vélos">Vélos</option>
	<option value="Véhicules Professionnels">Véhicules Professionnels</option>
	<option value="Bateaux">Bateaux</option>
	<option value="Pièces et Accessoires pour véhicules">Pièces et Accessoires pour véhicules</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="1000">-- IMMOBILIER --</option>
	<option value="Appartements">Appartements</option>
	<option value="Maisons et Villas">Maisons et Villas</option>
	<option value="Bureaux et Plateaux">Bureaux et Plateaux</option>
	<option value="Magasins, Commerces et Locaux industriels">Magasins, Commerces et Locaux industriels</option>
	<option value="Terrains et Fermes">Terrains et Fermes</option>
	<option value="Locations de vacances">Locations de vacances</option>
	<option value="Colocations">Colocations</option>
	<option value="Autre Immobilier">Autre Immobilier</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="3000">-- POUR LA MAISON ET JARDIN --</option>
	<option value="Electroménager et Vaisselles">Electroménager et Vaisselles</option>
	<option value="Meubles et Décoration">Meubles et Décoration</option>
	<option value="Jardin et Outils de bricolage">Jardin et Outils de bricolage</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="8000">-- HABILLEMENT ET BIEN ETRE --</option>
	<option value="Vêtements">Vêtements</option>
	<option value="Chaussures">Chaussures</option>
	<option value="Montres et Bijoux">Montres et Bijoux</option>
	<option value="Sacs et Accessoires">Sacs et Accessoires</option>
	<option value="3030">Vêtements pour enfant et bébé</option>
	<option value="3130">Equipements pour enfant et bébé</option>
	<option value="3070">Produits de beauté</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="4000">-- LOISIRS ET DIVERTISSEMENT --</option>
	<option value="4010">Sports et Loisirs</option>
	<option value="Animaux">Animaux</option>
	<option value="4070">Instruments de Musique</option>
	<option value="4060">Art et Collections</option>
	<option value="4050">Voyages et Billetterie</option>
	<option value="4040">Films, Livres, Magazines</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="6000">-- EMPLOI ET SERVICES --</option>
	<option value="6010">Offres d'emploi</option>
	<option value="6020">Demandes d'emploi</option>
	<option value="Stages">Stages</option>
	<option value="Services">Services</option>
	<option value="Cours et Formations">Cours et Formations</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="9000">-- ENTREPRISES --</option>
	<option value="6100">Business et Affaires commerciales</option>
	<option value="6090">Matériels Professionnels</option>
	<option value="6120">Stocks et Vente en gros</option>
	<option style="background-color:#dcdcc3; font-weight: bold;" value="7000">-- Autres --</option>
</select>

<select name="ville" class="form-control input-lg" style="width: 20%; display: inline-block;" id="inputState" class="form-control">
<option value="*" selected>Tout le Maroc</option>
<option value="Agadir"> Agadir</option>
<option value="Al Hoceïma"> Al Hoceïma</option>
<option value="Béni Mellal"> Béni Mellal</option>
<option value="El Jadida<"> El Jadida</option>
<option value="Errachidia"> Errachidia</option>
<option value="Fès"> Fès</option>
<option value="Kenitra"> Kénitra</option>
<option value="Khenifra"> Khénifra</option>
<option value="Khouribga"> Khouribga</option>
<option value="Larache"> Larache</option>
<option value="Marrakech"> Marrakech</option>
<option value="Meknès"> Meknès</option>
<option value="Nador"> Nador</option>
<option value="Ouarzazate"> Ouarzazate</option>
<option value="Oujda"> Oujda</option>
<option value="Rabat"> Rabat</option>
<option value="Safi"> Safi</option>
<option value="Settat"> Settat</option>
<option value="Salé"> Salé</option>
<option value="Tanger"> Tanger</option>
<option value="Taza"> Taza</option>
<option value="Tétouan"> Tétouan</option>
</select>
<div class="form-group" style="margin-left: 20%">
        <label><input name="genre" type="radio" value="offre" checked="checked">Offre</label>
    &nbsp;&nbsp;
      <label><input name="genre" type="radio" value="demande">Demande</label>
        

<li style="margin-left:46%;margin-top: 2%;display: inline-block;"><%= submit_tag "Rechercher", class:"z" %></li></div>

<% end %>

<br/><br/>

Otiva/app/views/pages/login.html.erb
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<% if session[:util_id] %>
	<%= render "pages/nav2" %>
	<h2>Vous êtes déjà authentifié !</h2>
	<span class="button-checkbox">
		<%= link_to 'Retour à l\'acceuil', root_path, class: "btn btn-link pull-right" %>
	</span>
<% else %>
	<%= render "pages/nav" %>
<div class="container">

<div class="row" style="margin-bottom:5%;margin-left: 20%;">
    <div class="col-xs-10 col-sm-6 col-md-4 col-sm-offset-2 col-md-offset-3">
			<%= form_tag "login", method: :post do %>
			<fieldset>
				<h2>Connexion</h2>
				<hr class="colorgraph">
				<div class="form-group">
                    <input type="text" name="name" id="name" class="form-control input-lg" placeholder="Nom d'utilisateur">
				</div>
				<div class="form-group">
                    <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Mot de passe">
				</div>
				<hr class="colorgraph">
				<div class="row">
                        <input style="background-color: #FE980F;" type="submit" class="btn btn-lg btn-success btn-block" value="Se connecter">	
				</div> <br/>
                Vous n'êtes pas encore inscrits ? <%= link_to 'Inscrivez-vous', inscription_path %>
					
			</fieldset>
			
	</div>
</div>
</div>
<% end %>
<% end %>